FROM m.daocloud.io/docker.io/library/python:3.12-slim
WORKDIR /app
ENV TZ="Asia/Shanghai"
COPY python/ /app/
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
EXPOSE 5000
CMD ["python", "rank_service.py", "lightgbm_rank_model.txt", "gru4rec_model.pth", "5000"]